name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure `pyhtmlify` and test dependencies are listed here

    - name: Install pyhtmlify
      run: |
        pip install .
    
    - name: Run pyhtmlify generate
      run: |
        pyhtmlify generate -f generated_html

    - name: List files in generated_html
      run: |
        echo "Listing files in generated_html:"
        find generated_html -type f

    - name: List files in expected_html
      run: |
        echo "Listing files in expected_html:"
        find expected_html -type f

    - name: Check HTML output
      run: |
        # Ensure both directories exist
        if [ ! -d "generated_html" ]; then
          echo "Directory 'generated_html' does not exist."
          exit 1
        fi

        if [ ! -d "expected_html" ]; then
          echo "Directory 'expected_html' does not exist."
          exit 1
        fi

        # Compare each generated file with its expected counterpart
        for file in $(find generated_html -type f); do
          filename=$(basename "$file")
          expected_file="expected_html/$filename"
          
          if [ -f "$expected_file" ]; then
            if ! diff "$file" "$expected_file"; then
              echo "Mismatch found in $filename"
              exit 1
            fi
          else
            echo "Expected file $expected_file does not exist."
            exit 1
          fi
        done

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: html-diff
        path: generated_html
