name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure `pyhtmlify` and test dependencies are listed here

    - name: Install pyhtmlify
      run: |
        pip install .
    
    - name: Run pyhtmlify generate
      run: |
        pyhtmlify generate -f generated_html

    - name: Check HTML output
      run: |
        # Define expected output HTML files directory
        mkdir -p expected_html
        # Compare generated HTML with expected HTML
        for file in generated_html/*.html; do
          filename=$(basename "$file")
          if ! diff "$file" "expected_html/$filename"; then
            echo "Mismatch found in $filename"
            exit 1
          fi
        done

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: html-diff
        path: generated_html